### ISSUE TITLE
Integration with NestJS

### ISSUE THREAD

**Issue by Gusb3ll** [nearform/mercurius-apollo-tracing#169]
I want to use this plugin with my current mercurius server which is on NestJS w/ fastify adapter here's my script

```ts
(async () => {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter()
  )

  await app.register(mercuriusTracing, {
    apiKey: '',
    graphRef: '',
  })

  await app.listen(3000, 'localhost')
})()
```

I got this error when I started the server

```
The dependency 'mercurius' of plugin 'mercuriusApolloTracing' is not registered
```
So I'm not sure if there's any way I could get this plugin setup with Nest or any guide for how to do the dependency injection would be helpful also, Thanks!

**Comment by stearm** [comment]
Hi @Gusb3ll, I don't see the [register call for the mercurius plugin](https://github.com/nearform/mercurius-apollo-tracing#usage) in your snippet. Is it missing?

**Comment by simoneb** [comment]
Closing as this seems to be an issue with the code posted missing mercurius' registration

**Comment by valmirphp** [comment]
@Gusb3ll I had the same problem, I discovered that you can call plugins that way.



```ts
import mercuriusTracing from "mercurius-apollo-tracing";

GraphQLModule.forRoot<MercuriusDriverConfig>({
  driver: MercuriusDriver,
  typePaths: ["./**/*.graphql"],
  graphiql: true,
  jit: 0,
  plugins: [
    {
      plugin: mercuriusTracing,
      options: {
        apiKey: "xxxx",
        graphRef: "xxx@current"
      }
    } as any
  ]
});
```
