### ISSUE TITLE
add maxUncompressedReportSize option

### ISSUE THREAD

**Issue by capaj** [nearform/mercurius-apollo-tracing#26]
https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#maxuncompressedreportsize

we should add this config option to avoid generating too much outgoing traffic on servers with high load.

Solution can be inspired by https://github.com/apollographql/apollo-server/blob/45be2704be5498595bd7a24ca7f330e59f628e3c/packages/apollo-server-core/src/plugin/usageReporting/stats.ts#L32

**Comment by simoneb** [comment]
@capaj when adding issues let's add them to our project board so they're visible
