### ISSUE TITLE
Generalize library for other APM tools

### ISSUE THREAD

**Issue by eduhenke** [nearform/mercurius-apollo-tracing#46]
I am integrating with elastic APM, and I am using this repo as a guide to see how to do that.

But I am seeing that a lot of things are already done here, hookIntoSchemaResolvers, TraceBuilderStore, ...
Could there be any way to make this library(or create another one) more general(to support other APM tools).

Where I can simply feed my startSpan and endSpan functions, with maybe some customization on which fields/labels/tags I want to set.

Being an outsider it seems like 90% of the work is common between all reporting tools, and 10% of the work is specific to the Apollo APM.

**Comment by simoneb** [comment]
There's most likely a chance to generalize this. We built it to support Apollo Studio primarily, hence why the code is not factored in a way to be used for other purposes, but we would certainly be interested in supporting other APMs.

**Comment by drakhart** [comment]
After assessing this for a while, my conclusion is that it'd be easier to create a new plugin from scratch to target the way other APMs usually work (by sending individual metrics) vs. how Apollo Studio works (by [sending full reports](https://github.com/nearform/mercurius-apollo-tracing/blob/10d45c087f0eb0cca6ae31d1ce338a70aa9c36e8/tap-snapshots/src/e2e.spec.ts.test.cjs#L30)).

I started the rewrite by creating an abstraction of the `ApolloTraceBuilder` class, then another for Apollo's `Trace.Node` class to store each node information, so in the end one could digest each node and send it to a specific APM as a metric; but separating all the Apollo logic and going metric vs report is proving to be very time consuming and still I'm not sure if the outcome will be really usable on any target APM.

By the way, DataDog already has an [Apollo Studio integration](https://docs.datadoghq.com/integrations/apollo/) so it can potentially use this very same library. As for other APMs, and as I already mentioned, I strongly believe it'd be easier to write a new plugin.
